let's create a model which can predict the crop yeild for different region using previous data using numpy arrays.

In [1]:
import numpy as np

In [2]:
climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])

In [3]:
climate_data.shape

(5, 3)

In [4]:
weights = np.array([0.3,0.2,0.5])

In [5]:
weights.shape

(3,)

In [6]:
## 3d array
arr3 = np.array([[[11,12,13],
                 [13,14,15]]
                ,[[15,16,17],
                  [17,18,19]]])

In [7]:
arr3.shape

(2, 2, 3)

In [8]:
arr3.dtype

dtype('int64')

In [9]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [10]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [11]:
## Working with CSV data files
import urllib.request

In [12]:
## Array indexing and slicing
arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,19]],
    [[15,16,17,21],
     [63,92,36,18]],
    [[98,32,81,23],
     [17,18,19.5,43]],
])

In [13]:
arr3.shape

(3, 2, 4)

In [14]:
arr3[1,1,2]

np.float64(36.0)

In [15]:
## Subarray using ranges
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])